language: android
sudo: required
android:
  components:
    - tools
    - build-tools-23.0.3
    - build-tools-23.0.2
    - build-tools-23.0.1
    - android-23
    - android-22
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - '.*intel.+'
before_install:
  - chmod +x gradlew
  - git submodule update --init --recursive
  - git update-index --chmod=+x gradlew
  - chmod +x gradlew
install:
  - ./gradlew
script:
  - ./gradlew assembleDebug --stacktrace
